# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

Feature: A new shopping cart

  Scenario: Step errors
    Given A request with id " 0a15d511-4a1e-44ce-89f4-85fb09c9a0a9" is registered into the system with the verification code "111111"
