# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

Feature: My feature 1
  As a customer
  I want to have discount codes

  Scenario: My scenario 3

  Scenario: My Scenario 1 Copy renamed 2
    Given an outline scenario
      | C1  |
      | C11 |
    When a file is deleted
    And i am stupid
    And i want to recover it

  Scenario Outline: My Scenario 1 a
    Given an outline scenario
      | C1  |  |
      | C11 |  |
      |     |  |
    When a file is deleted
    And i am stupid
    And i want to recover it

    Examples:
      | Example 1 |
      | Val 1     |

  Scenario Outline: My Scenario 1 Copy
    Given an outline scenario
      | C1  |
      | C11 |
    When a file is deleted
    And i am stupid
    And i want to recover it

    Examples:
      | Example 1 |
      | Val 1     |

  @tag2
  Scenario Outline: My Scenario 2 rename 3
    Given user 1
    When when 2

    Examples:
      | ex3 |
      | c3  |

  Scenario: My Scenario
