# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Special characters on names
  As an api client
  I want to be able to send special characters on names

@t1
  Scenario Outline: valid names on creation
    Given XXX1
    When I request creation of new blueprint with following data
      | name   | project   |
      | <NAME> | project 1 |
    Then the response status code is 201

    Examples:
      | NAME      |
      | AaAa 12   |
      | asdf-sadf |
      | asdf_sadf |
      | asdf.sadf |
