# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: My feature 4
  As a customer
  I want to have discount codes

@wer @wer
  Scenario: My scenario 3
    Given rewrew
    When dsgfs  fv
    Then acdfsgvcdsvg vvfsd

@draft @draft_scenario
  Scenario: My Scenario
    Given faefae1
      |  |  |  |
      |  |  |  |
      |  |  |  |
